spring.application.name=qlcv

# MongoDB
# Mongo_Db_Url
spring.data.mongodb.uri=mongodb+srv://admin:admin@musicbox.nlgmhuq.mongodb.net/QLCV?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# JWT
qlcv.app.jwtSecret=qlcvSecretKeyForJwtAuthenticationThisShouldBeALongSecretKey1234567890
qlcv.app.jwtExpirationMs=86400000
